### ISSUE TITLE
ERROR: invalid mask `48' specified

### ISSUE THREAD

**Issue by constb** [freemedia-tech/iptables-rugov-block#3]
while installing on ubuntu 22.04 I get an error:

```
iptables v1.8.7 (nf_tables): invalid mask `48' specified
```

caused by the following lines in `blacklist.txt`:

```
2a0c:a9c7:156::/48
2a0c:a9c7:157::/48
2a0c:a9c7:158::/48
```

**Comment by freemediatech** [comment]
The commit 284b338 solves the issue. Run `sudo ./install.sh` after updating the repo locally. If all is fine - feel free to close the issue @constb
